# Site settings
title: WFP Editorial 
email: ""
description: ""
baseurl: "." # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

exclude: ["*.sublime-*", "*.sh", "*.yml", "*.DS_*"]

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

category-list: [Audience, Basics, Sentence Structure, Consistency, Usage, Vocabulary, Abbreviations and Acronyms, Spelling and Terminology, Word Treatment; Ellipsis, Detail, Numbers and Units, Place Names, Reference, Bibliographies, Tables]

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

sass:
  style: expanded